version: "3.7"
services:
  site-parser-postgres:
    image: postgres:11
    container_name: site-parser-postgres
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: websites
  site-parser-redis:
    image: redis
    container_name: site-parser-redis
    ports:
      - 6379:6379
volumes:
  postgres-data:
    external: true
